name: Label issue

on:
  issues:
    types: [edited, opened, reopened]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-24.04
    if: |
      (github.event.action == 'edited' && contains(github.event.issue.labels.*.name, 'invalid')) ||
      github.event.action == 'opened' ||
      github.event.action == 'reopened'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Label issue
      run: ./label.py
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        ISSUE_BODY: ${{ steps.issue-parser.outputs.parsed-issue }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
